server:
  port: 8088
  spring:
    redis:
      host: 192.168.1.140
      port: 6379
      password:
      timeout: 36000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
spring:
  rabbitmq:
    host: 192.168.1.140
    port: 5672
    username: root
    password: root
  application:
    name: cloudribbon
thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
