server:
  port: 8089
spring:
  redis:
    host: 192.168.1.129
    port: 6379
    password:
    timeout: 36000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  application:
    name: cloudribbon
  rabbitmq:
    host: 192.168.1.129
    port: 5672
    username: root
    password: root
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
feign:
    hystrix:
      enabled: true